# OM-File Format Example

In [42]:
# imports
import omfilesrspy as om
import numpy as np

# generate some random test data
data = np.random.random((10, 10, 10)).astype(np.float32) * 100

### Basic Usage Example for 3 dimensional data!

In [43]:
# Simple write example
writer = om.OmFilePyWriter("data.om")
writer.write_array_f32(data, chunks=(5, 5, 5), scale_factor=100, add_offset=0)

# Simple read example
reader = om.OmFilePyReader("data.om")
subset = reader[0:5, 0:5, ...]
print(f"Shape: {subset.shape}")
print(subset)

Shape: (5, 5, 10)
[[[89.02  3.32 95.38 71.07 34.37 96.53 69.08 85.96 67.77 38.73]
  [34.67 31.64 54.28 82.5  32.41  4.8  54.08 87.42  9.17 56.75]
  [68.89 13.02 58.74 48.72 29.78 49.59  9.67 41.05 14.89  0.63]
  [16.33  3.82 45.31 75.48  0.74 69.09 48.37 82.56 30.86 63.39]
  [ 8.99 46.82 96.88 29.94 29.8  83.71 21.33 71.24 94.01 33.6 ]]

 [[90.78 10.42 20.23 74.1  18.37 91.44 75.73 57.98 60.37 76.95]
  [31.93 60.42 49.19 72.74 51.29 18.15 64.83 60.17 16.26 44.43]
  [78.01 40.66 30.09 63.5  21.98 59.24 36.25 52.32 70.82 42.7 ]
  [63.98 28.99  6.94 35.19 27.01  0.78 66.06 61.8  34.53 97.99]
  [ 4.98 53.32 89.89 87.41 38.51 11.45  0.81 89.66 83.64 49.15]]

 [[31.86 36.1  41.97  0.67 40.27 21.59 82.19 35.12 67.23 75.01]
  [38.99 11.64 72.39 23.37 46.55  2.14 28.94 78.45 77.86 18.04]
  [79.68 18.3  15.7  80.55 21.42 37.43 98.38 43.46 76.13 91.11]
  [ 6.46 59.04 38.24 80.56 69.81  3.37 81.2  93.4  23.58 39.71]
  [18.78 33.62 85.74  5.11 35.69 62.08 62.96 19.24  7.97 50.79]]

 [[67.48 23.8  4

### Example: Multiple dimensions flattened into a single dimension.

Note that this is dangerous, because the user will most likely not 100% understand how the data is layed out in the backend/file. He might end up with the wrong data...
1. First example shows how it is done in the wrong way.
2. Second example shows how it could be done correctly.

In [44]:
# Flatten data to 1D
flattened_data = data.flatten()
# Write to file
writer = om.OmFilePyWriter("data.om")
writer.write_array_f32(flattened_data, chunks=(100,), scale_factor=100, add_offset=0)

# Read data from file
reader = om.OmFilePyReader("data.om")
# Read data - NOTE: This is not really the data the user is interested in!
read_data = reader[0:250]

# Reshape back to original dimensions
reshaped_data = read_data.reshape(5, 5, 10)
# Display results
print(f"Shape: {reshaped_data.shape}")
print(reshaped_data)

Shape: (5, 5, 10)
[[[89.02  3.32 95.38 71.07 34.37 96.53 69.08 85.96 67.77 38.73]
  [34.67 31.64 54.28 82.5  32.41  4.8  54.08 87.42  9.17 56.75]
  [68.89 13.02 58.74 48.72 29.78 49.59  9.67 41.05 14.89  0.63]
  [16.33  3.82 45.31 75.48  0.74 69.09 48.37 82.56 30.86 63.39]
  [ 8.99 46.82 96.88 29.94 29.8  83.71 21.33 71.24 94.01 33.6 ]]

 [[46.7   2.09 91.17  9.45 23.3  12.07 82.01  2.05 52.37  9.04]
  [59.54 11.01 12.81  6.18 59.78 38.57 25.57 13.01 61.8   1.84]
  [86.92 43.86 28.04 53.3  53.44 57.51 42.74 45.61 21.04  8.26]
  [40.13  7.16 38.51 23.15 36.51 32.34 18.39 35.74 88.54 46.51]
  [67.66 78.45 68.85 79.49 45.81 71.23 41.95  7.34 92.98 38.24]]

 [[90.78 10.42 20.23 74.1  18.37 91.44 75.73 57.98 60.37 76.95]
  [31.93 60.42 49.19 72.74 51.29 18.15 64.83 60.17 16.26 44.43]
  [78.01 40.66 30.09 63.5  21.98 59.24 36.25 52.32 70.82 42.7 ]
  [63.98 28.99  6.94 35.19 27.01  0.78 66.06 61.8  34.53 97.99]
  [ 4.98 53.32 89.89 87.41 38.51 11.45  0.81 89.66 83.64 49.15]]

 [[ 0.3  74.61 4

In [47]:
# Flatten data to 1D
flattened_data = data.flatten()
# Write to file
writer = om.OmFilePyWriter("data.om")
writer.write_array_f32(flattened_data, chunks=(100,), scale_factor=100, add_offset=0)

# Read data from file
reader = om.OmFilePyReader("data.om")

# Read data - 
# NOTE: Here we read the data we are really interested in. 
# Note that offloading such a responsibility to the user is not good!
segments = [
    reader[0:50],
    reader[100:150],
    reader[200:250],
    reader[300:350],
    reader[400:450],
]

# Concatenate all segments into a single array
read_data = np.concatenate(segments)


# Reshape back to original dimensions
reshaped_data = read_data.reshape(5, 5, 10)
# Display results
print(f"Shape: {reshaped_data.shape}")
print(reshaped_data)

Shape: (5, 5, 10)
[[[89.02  3.32 95.38 71.07 34.37 96.53 69.08 85.96 67.77 38.73]
  [34.67 31.64 54.28 82.5  32.41  4.8  54.08 87.42  9.17 56.75]
  [68.89 13.02 58.74 48.72 29.78 49.59  9.67 41.05 14.89  0.63]
  [16.33  3.82 45.31 75.48  0.74 69.09 48.37 82.56 30.86 63.39]
  [ 8.99 46.82 96.88 29.94 29.8  83.71 21.33 71.24 94.01 33.6 ]]

 [[90.78 10.42 20.23 74.1  18.37 91.44 75.73 57.98 60.37 76.95]
  [31.93 60.42 49.19 72.74 51.29 18.15 64.83 60.17 16.26 44.43]
  [78.01 40.66 30.09 63.5  21.98 59.24 36.25 52.32 70.82 42.7 ]
  [63.98 28.99  6.94 35.19 27.01  0.78 66.06 61.8  34.53 97.99]
  [ 4.98 53.32 89.89 87.41 38.51 11.45  0.81 89.66 83.64 49.15]]

 [[31.86 36.1  41.97  0.67 40.27 21.59 82.19 35.12 67.23 75.01]
  [38.99 11.64 72.39 23.37 46.55  2.14 28.94 78.45 77.86 18.04]
  [79.68 18.3  15.7  80.55 21.42 37.43 98.38 43.46 76.13 91.11]
  [ 6.46 59.04 38.24 80.56 69.81  3.37 81.2  93.4  23.58 39.71]
  [18.78 33.62 85.74  5.11 35.69 62.08 62.96 19.24  7.97 50.79]]

 [[67.48 23.8  4